# ansible/playbook.yml

- name: Configure Server and Deploy Sendmate Container
  hosts: all
  become: yes # Execute commands with sudo
  tasks:
    - name: Update all system packages
      yum:
        name: '*'
        state: latest

    - name: Install Docker engine
      yum:
        name: docker
        state: present

    - name: Start and enable the Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add the ec2-user to the 'docker' group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull the latest Sendmate image from Docker Hub
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/sendmate:latest"
        source: pull

    - name: Stop any existing Sendmate container
      community.docker.docker_container:
        name: sendmate_app
        state: absent

    - name: Run the Sendmate container with all required environment variables
      community.docker.docker_container:
        name: sendmate_app
        image: "{{ dockerhub_username }}/sendmate:latest"
        state: started
        restart_policy: always
        ports:
          - "80:5000"
        env:
          # Pass all secrets from Ansible to the container's environment
          MONGO_URI: "{{ mongo_uri }}"
          GOOGLE_CLIENT_ID: "{{ google_client_id }}"
          GOOGLE_CLIENT_SECRET: "{{ google_client_secret }}"
          AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
          AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
          AWS_REGION: "{{ aws_region }}"
          AWS_BUCKET_NAME: "{{ aws_bucket_name }}"
          PORT: "5000"
