# ansible/playbook.yml

- name: Configure Server and Deploy Sendmate Container
  hosts: all
  become: yes # Execute commands with sudo
  tasks:
    - name: Update all system packages
      yum:
        name: '*'
        state: latest

    - name: Install Docker engine
      yum:
        name: docker
        state: present

    - name: Start and enable the Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add the ec2-user to the 'docker' group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Pull the latest Sendmate image from Docker Hub
      community.docker.docker_image:
        name: "{{ dockerhub_username }}/sendmate:latest"
        source: pull

    - name: Stop any existing Sendmate container
      community.docker.docker_container:
        name: sendmate_app
        state: absent

    - name: Run the Sendmate container with correct environment variables
      community.docker.docker_container:
        name: sendmate_app
        image: "{{ dockerhub_username }}/sendmate:latest"
        state: started
        restart_policy: always
        ports:
          - "80:5000" # CORRECTED: Mapped host port 80 to container port 5000
        env:
          # These variable names MUST match what's in your app.js
          MONGO_URL: "{{ mongo_url }}"
          GOOGLE_CLIENT_ID: "{{ google_client_id }}"
          GOOGLE_CLIENT_SECRET: "{{ google_client_secret }}"
          SECRET: "{{ secret }}"
