# .github/workflows/ansible.yml

name: 2. Deploy Application

on:
  workflow_call:
    inputs:
      ip_address:
        required: true
        type: string
    # This block declares all the secrets the workflow needs to receive
    secrets:
      EC2_SSH_PRIVATE_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      MONGO_URI:
        required: true
      GOOGLE_CLIENT_ID:
        required: true
      GOOGLE_CLIENT_SECRET:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_BUCKET_NAME:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Run Ansible Deployment
        env:
          # These secrets are now passed securely from the calling workflow
          ANSIBLE_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
          IP_ADDRESS: ${{ inputs.ip_address }}
        run: |
          # Install necessary tools
          sudo apt-get update
          sudo apt-get install -y ansible sshpass
          
          echo "✅ Received IP Address from trigger: $IP_ADDRESS"

          # Validate the IP address
          if [[ ! "$IP_ADDRESS" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Error: Invalid or empty IP address received from trigger."
            exit 1
          fi

          echo "$ANSIBLE_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          sleep 20

          ansible-playbook ansible/playbook.yml \
            --inventory "$IP_ADDRESS," \
            --private-key private_key.pem \
            --user ec2-user \
            --extra-vars "dockerhub_username=${{ secrets.DOCKERHUB_USERNAME }} mongo_uri='${{ secrets.MONGO_URI }}' google_client_id='${{ secrets.GOOGLE_CLIENT_ID }}' google_client_secret='${{ secrets.GOOGLE_CLIENT_SECRET }}' aws_access_key_id='${{ secrets.AWS_ACCESS_KEY_ID }}' aws_secret_access_key='${{ secrets.AWS_SECRET_ACCESS_KEY }}' aws_region='ap-south-1' aws_bucket_name='${{ secrets.AWS_BUCKET_NAME }}'"
          
          rm private_key.pem
