# .github/workflows/terraform.yml

name: 1. Provision Infrastructure

on:
  push:
    branches:
      - master

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sendmate:latest

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="ec2_key_pair_name=${{ secrets.EC2_KEY_PAIR_NAME }}"
        working-directory: ./terraform

      # Get the IP address as a step output
      - name: Get Terraform Outputs
        id: get_ip
        run: echo "ip_address=$(terraform -chdir=terraform output -raw public_ip)" >> $GITHUB_OUTPUT
        working-directory: ./terraform

      # Call the Ansible workflow and pass the IP and secrets
      - name: Trigger Ansible Deployment Workflow
        uses: ./.github/workflows/ansible.yml
        with:
          ip_address: ${{ steps.get_ip.outputs.ip_address }}
        secrets: inherit # This securely passes all repository secrets to the called workflow
